name: Build matrix

on:
  push:
      branches: [main, master]
  pull_request:
      branches: [main, master]
  workflow_call:
    outputs:
        deb-name:
          value: ${{ jobs.build.outputs.deb-name }}
        app-image-name:
          value: ${{ jobs.build.outputs.app-image-name }}
jobs:
  build:
      strategy:
          matrix:
              # os: [ubuntu-latest, macos-latest, windows-latest]
              os: [ubuntu-latest]
      uses: ./.github/workflows/build.yml
      with:
          os: ${{ matrix.os }}
      secrets: inherit
